version: '3'

services:
  ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map container port 80 to host port 3000 for React frontend

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Map container port 3000 to host port 5000 for API backend
    depends_on:
      - db  # Ensure API starts after the database service

  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432 for PostgreSQL
    volumes:
      - db_data:/var/lib/postgresql/data  # Mount named volume for database data storage

volumes:
  db_data:  # Define named volume for PostgreSQL data